background            #1a1816
background_opacity    0.85
background_blur       1
hide_window_decorations yes
cursor                #e0ac69
cursor_text_color     #1a1816
font_family      JetBrainsMono Nerd Font
font_size        11.0
window_padding_width 10
include ~/.cache/wal/colors-kitty.conf
